# Generated by Django 3.2.9 on 2021-11-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('developerid', models.IntegerField(db_column='DeveloperID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=45, null=True)),
                ('lname', models.CharField(blank=True, db_column='Lname', max_length=45, null=True)),
                ('developerimg', models.CharField(blank=True, db_column='developerIMG', max_length=255, null=True)),
            ],
            options={
                'db_table': 'developers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(db_column='GameID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('releasedate', models.CharField(blank=True, db_column='ReleaseDate', max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=3, null=True)),
                ('gameimg', models.CharField(blank=True, db_column='gameIMG', max_length=2555, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gname', models.CharField(db_column='GName', max_length=45, primary_key=True, serialize=False)),
                ('genre_tag', models.CharField(blank=True, db_column='Genre/Tag', max_length=45, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multiplayer',
            fields=[
                ('players', models.IntegerField(db_column='Players', primary_key=True, serialize=False)),
                ('mode', models.CharField(blank=True, db_column='Mode', max_length=45, null=True)),
            ],
            options={
                'db_table': 'multiplayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platformid', models.IntegerField(db_column='PlatformID', primary_key=True, serialize=False)),
                ('system', models.CharField(blank=True, db_column='System', max_length=45, null=True)),
            ],
            options={
                'db_table': 'platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rateno', models.IntegerField(db_column='RateNo', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
