# Generated by Django 3.2.9 on 2021-11-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savegame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreAssociated',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_id', models.IntegerField()),
            ],
            options={
                'db_table': 'genre_associated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformAssociatied',
            fields=[
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='savegame.platform')),
                ('release_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'platform_associatied',
                'managed': False,
            },
        ),
    ]
